# Converted for MMDetection 3.x.
# The model definition is kept from the old config as much as possible,
# while data pipelines, dataloaders, evaluators and schedules use 3.x APIs.
# NOTE: The old NWD config referenced RankingAssigner and BboxDistanceMetric,
# which are not present in this MMDetection 3.x checkout. The RPN assigner
# has been reset to the standard MaxIoUAssigner so the config can run.

_base_ = ['../mmdetection/configs/_base_/default_runtime.py']

custom_imports = dict(
    imports=['mmdet.datasets.aitod', 'mmdet.models', 'mmdet.models.necks.hs_fpn'],
    allow_failed_imports=False)

model = {'type': 'CascadeRCNN',
 'backbone': {'type': 'ResNet',
              'depth': 50,
              'num_stages': 4,
              'out_indices': (0, 1, 2, 3),
              'frozen_stages': 1,
              'norm_cfg': {'type': 'BN', 'requires_grad': True},
              'norm_eval': True,
              'style': 'pytorch',
              'init_cfg': {'type': 'Pretrained',
                           'checkpoint': 'torchvision://resnet50'}},
 'neck': {'type': 'HS_FPN',
          'in_channels': [256, 512, 1024, 2048],
          'out_channels': 256,
          'num_outs': 5,
          'ratio': (0.25, 0.25)},
 'rpn_head': {'type': 'RPNHead',
              'in_channels': 256,
              'feat_channels': 256,
              'anchor_generator': {'type': 'AnchorGenerator',
                                   'scales': [2],
                                   'ratios': [0.33, 0.5, 1.0, 2.0, 3.0],
                                   'strides': [4, 8, 16, 32, 64]},
              'bbox_coder': {'type': 'DeltaXYWHBBoxCoder',
                             'target_means': [0.0, 0.0, 0.0, 0.0],
                             'target_stds': [1.0, 1.0, 1.0, 1.0]},
              'loss_cls': {'type': 'CrossEntropyLoss',
                           'use_sigmoid': True,
                           'loss_weight': 1.0},
              'loss_bbox': {'type': 'SmoothL1Loss',
                            'beta': 0.1111111111111111,
                            'loss_weight': 1.0}},
 'roi_head': {'type': 'CascadeRoIHead',
              'num_stages': 3,
              'stage_loss_weights': [1, 0.5, 0.25],
              'bbox_roi_extractor': {'type': 'SingleRoIExtractor',
                                     'roi_layer': {'type': 'RoIAlign',
                                                   'output_size': 7,
                                                   'sampling_ratio': 0},
                                     'out_channels': 256,
                                     'featmap_strides': [4, 8, 16, 32]},
              'bbox_head': [{'type': 'Shared2FCBBoxHead',
                             'in_channels': 256,
                             'fc_out_channels': 1024,
                             'roi_feat_size': 7,
                             'num_classes': 8,
                             'bbox_coder': {'type': 'DeltaXYWHBBoxCoder',
                                            'target_means': [0.0,
                                                             0.0,
                                                             0.0,
                                                             0.0],
                                            'target_stds': [0.1,
                                                            0.1,
                                                            0.2,
                                                            0.2]},
                             'reg_class_agnostic': True,
                             'loss_cls': {'type': 'CrossEntropyLoss',
                                          'use_sigmoid': False,
                                          'loss_weight': 1.0},
                             'loss_bbox': {'type': 'SmoothL1Loss',
                                           'beta': 1.0,
                                           'loss_weight': 1.0}},
                            {'type': 'Shared2FCBBoxHead',
                             'in_channels': 256,
                             'fc_out_channels': 1024,
                             'roi_feat_size': 7,
                             'num_classes': 8,
                             'bbox_coder': {'type': 'DeltaXYWHBBoxCoder',
                                            'target_means': [0.0,
                                                             0.0,
                                                             0.0,
                                                             0.0],
                                            'target_stds': [0.05,
                                                            0.05,
                                                            0.1,
                                                            0.1]},
                             'reg_class_agnostic': True,
                             'loss_cls': {'type': 'CrossEntropyLoss',
                                          'use_sigmoid': False,
                                          'loss_weight': 1.0},
                             'loss_bbox': {'type': 'SmoothL1Loss',
                                           'beta': 1.0,
                                           'loss_weight': 1.0}},
                            {'type': 'Shared2FCBBoxHead',
                             'in_channels': 256,
                             'fc_out_channels': 1024,
                             'roi_feat_size': 7,
                             'num_classes': 8,
                             'bbox_coder': {'type': 'DeltaXYWHBBoxCoder',
                                            'target_means': [0.0,
                                                             0.0,
                                                             0.0,
                                                             0.0],
                                            'target_stds': [0.033,
                                                            0.033,
                                                            0.067,
                                                            0.067]},
                             'reg_class_agnostic': True,
                             'loss_cls': {'type': 'CrossEntropyLoss',
                                          'use_sigmoid': False,
                                          'loss_weight': 1.0},
                             'loss_bbox': {'type': 'SmoothL1Loss',
                                           'beta': 1.0,
                                           'loss_weight': 1.0}}]},
 'train_cfg': {'rpn': {'assigner': {'type': 'MaxIoUAssigner',
                                    'pos_iou_thr': 0.7,
                                    'neg_iou_thr': 0.3,
                                    'min_pos_iou': 0.3,
                                    'match_low_quality': True,
                                    'ignore_iof_thr': -1,
                                    'gpu_assign_thr': 512},
                       'sampler': {'type': 'RandomSampler',
                                   'num': 256,
                                   'pos_fraction': 0.5,
                                   'neg_pos_ub': -1,
                                   'add_gt_as_proposals': False},
                       'allowed_border': 0,
                       'pos_weight': -1,
                       'debug': False},
               'rpn_proposal': {'nms_pre': 3000,
                                'max_per_img': 3000,
                                'nms': {'type': 'nms', 'iou_threshold': 0.7},
                                'min_bbox_size': 0},
               'rcnn': [{'assigner': {'type': 'MaxIoUAssigner',
                                      'pos_iou_thr': 0.5,
                                      'neg_iou_thr': 0.5,
                                      'min_pos_iou': 0.5,
                                      'match_low_quality': False,
                                      'ignore_iof_thr': -1,
                                      'gpu_assign_thr': 512},
                         'sampler': {'type': 'RandomSampler',
                                     'num': 512,
                                     'pos_fraction': 0.25,
                                     'neg_pos_ub': -1,
                                     'add_gt_as_proposals': True},
                         'pos_weight': -1,
                         'debug': False},
                        {'assigner': {'type': 'MaxIoUAssigner',
                                      'pos_iou_thr': 0.6,
                                      'neg_iou_thr': 0.6,
                                      'min_pos_iou': 0.6,
                                      'match_low_quality': False,
                                      'ignore_iof_thr': -1,
                                      'gpu_assign_thr': 512},
                         'sampler': {'type': 'RandomSampler',
                                     'num': 512,
                                     'pos_fraction': 0.25,
                                     'neg_pos_ub': -1,
                                     'add_gt_as_proposals': True},
                         'pos_weight': -1,
                         'debug': False},
                        {'assigner': {'type': 'MaxIoUAssigner',
                                      'pos_iou_thr': 0.7,
                                      'neg_iou_thr': 0.7,
                                      'min_pos_iou': 0.7,
                                      'match_low_quality': False,
                                      'ignore_iof_thr': -1,
                                      'gpu_assign_thr': 512},
                         'sampler': {'type': 'RandomSampler',
                                     'num': 512,
                                     'pos_fraction': 0.25,
                                     'neg_pos_ub': -1,
                                     'add_gt_as_proposals': True},
                         'pos_weight': -1,
                         'debug': False}]},
 'test_cfg': {'rpn': {'nms_pre': 3000,
                      'max_per_img': 3000,
                      'nms': {'type': 'nms', 'iou_threshold': 0.7},
                      'min_bbox_size': 0},
              'rcnn': {'score_thr': 0.05,
                       'nms': {'type': 'nms', 'iou_threshold': 0.5},
                       'max_per_img': 3000}},
 'data_preprocessor': {'type': 'DetDataPreprocessor',
                       'mean': [123.675, 116.28, 103.53],
                       'std': [58.395, 57.12, 57.375],
                       'bgr_to_rgb': True,
                       'pad_size_divisor': 32}}

dataset_type = 'AITODDataset'
data_root = ''
backend_args = None
aitod_metainfo = dict(classes=('airplane',
 'bridge',
 'storage-tank',
 'ship',
 'swimming-pool',
 'vehicle',
 'person',
 'wind-mill'), palette=[(220, 20, 60),
 (119, 11, 32),
 (0, 0, 142),
 (0, 0, 230),
 (106, 0, 228),
 (0, 60, 100),
 (0, 80, 100),
 (0, 0, 70)])

train_pipeline = [{'type': 'LoadImageFromFile', 'backend_args': backend_args},
 {'type': 'LoadAnnotations', 'with_bbox': True},
 {'type': 'Resize', 'scale': (800, 800), 'keep_ratio': True},
 {'type': 'RandomFlip', 'prob': 0.5},
 {'type': 'PackDetInputs'}]

test_pipeline = [{'type': 'LoadImageFromFile', 'backend_args': backend_args},
 {'type': 'Resize', 'scale': (800, 800), 'keep_ratio': True},
 {'type': 'LoadAnnotations', 'with_bbox': True},
 {'type': 'PackDetInputs',
  'meta_keys': ('img_id',
                'img_path',
                'ori_shape',
                'img_shape',
                'scale_factor')}]

train_dataloader = {'batch_size': 1,
 'num_workers': 2,
 'persistent_workers': True,
 'sampler': {'type': 'DefaultSampler', 'shuffle': True},
 'batch_sampler': {'type': 'AspectRatioBatchSampler'},
 'dataset': {'type': dataset_type,
             'data_root': data_root,
             'ann_file': 'AI-TOD/annotations/aitod_trainval_v1.json',
             'data_prefix': {'img': 'AI-TOD/trainval/images'},
             'metainfo': aitod_metainfo,
             'filter_cfg': {'filter_empty_gt': True, 'min_size': 1},
             'pipeline': train_pipeline,
             'backend_args': backend_args}}

val_dataloader = {'batch_size': 1,
 'num_workers': 2,
 'persistent_workers': True,
 'drop_last': False,
 'sampler': {'type': 'DefaultSampler', 'shuffle': False},
 'dataset': {'type': dataset_type,
             'data_root': data_root,
             'ann_file': 'AI-TOD/annotations/aitod_test_v1.json',
             'data_prefix': {'img': 'AI-TOD/test/images'},
             'metainfo': aitod_metainfo,
             'test_mode': True,
             'pipeline': test_pipeline,
             'backend_args': backend_args}}
test_dataloader = val_dataloader

val_evaluator = {'type': 'CocoMetric',
 'ann_file': 'AI-TOD/annotations/aitod_test_v1.json',
 'metric': 'bbox',
 'format_only': False,
 'backend_args': backend_args}
test_evaluator = val_evaluator

train_cfg = dict(type='EpochBasedTrainLoop', max_epochs=12, val_interval=12)
val_cfg = dict(type='ValLoop')
test_cfg = dict(type='TestLoop')

param_scheduler = [
    dict(type='LinearLR', start_factor=0.001, by_epoch=False, begin=0, end=500),
    dict(type='MultiStepLR', begin=0, end=12, by_epoch=True, milestones=[8, 11], gamma=0.1),
]

optim_wrapper = dict(
    type='OptimWrapper',
    optimizer=dict(type='SGD', lr=0.005, momentum=0.9, weight_decay=0.0001))

default_hooks = dict(
    logger=dict(type='LoggerHook', interval=50),
    checkpoint=dict(type='CheckpointHook', interval=3, save_best='auto'))
custom_hooks = [dict(type='NumClassCheckHook')]

env_cfg = dict(
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    dist_cfg=dict(backend='nccl'))

log_level = 'INFO'
load_from = None
resume = False
work_dir = 'work_dirs/cascade_rcnn_r50_aitod_nwd'
randomness = dict(seed=1029399514, deterministic=False)
auto_scale_lr = dict(enable=False, base_batch_size=16)
